[package]
name = "chrome_leap-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.23", features = ["native-tls"] }

rcgen = "0.9"
quinn = "0.11"
rustls = "0.23"